
[project]
name = "catamaranswaps"

[[project.requirements]]
contract_id = "SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait"

[[project.requirements]]
contract_id = "SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.clarity-bitcoin-lib-v1"

[[project.requirements]]
contract_id = "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard"

[[project.requirements]]
contract_id = "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.send-many-memo"

[contracts.btc-ft-swap]
path = "contracts/btc-ft-swap.clar"
depends_on = []

[contracts.btc-nft-swap]
path = "contracts/btc-nft-swap.clar"
depends_on = []

[contracts.btc-stx-swap]
path = "contracts/btc-stx-swap.clar"
depends_on = []

[contracts.stx-ft-swap]
path = "contracts/stx-ft-swap.clar"
depends_on = []

[contracts.clarity-bitcoin]
path = "contracts/clarity-bitcoin.clar"
depends_on = []

[contracts.fixed-fees]
path = "contracts/fixed-fees.clar"
depends_on = []

[contracts.fun-token]
path = "contracts/ft.clar"
depends_on = []

[notebooks]
